# Generated by Django 3.2 on 2021-05-07 23:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('acg_serial', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acg_code', models.BigIntegerField(unique=True)),
                ('acg_name', models.CharField(max_length=200)),
                ('acg_level', models.IntegerField()),
                ('tot_credit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tot_debit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=11)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='accounting.accountgroup')),
            ],
        ),
        migrations.CreateModel(
            name='AccountMaster',
            fields=[
                ('acc_serial', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acc_code', models.BigIntegerField(unique=True)),
                ('acc_name_en', models.CharField(max_length=200)),
                ('acc_name_ar', models.CharField(max_length=200)),
                ('acc_level', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('opening_credit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('opening_debit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=11)),
                ('can_edit', models.BooleanField(default=True)),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Accounts_master', to='accounting.accountgroup')),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_title', models.CharField(blank=True, max_length=150)),
                ('Bank_Account_no', models.CharField(max_length=50)),
                ('bank_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bankmaster')),
                ('phone_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.phonebook')),
                ('supplier_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='accounting.accountmaster')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('overdays_count', models.IntegerField()),
                ('master_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.masterbranches')),
                ('supplier_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.suppliermaster')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_title', models.CharField(blank=True, max_length=150)),
                ('account_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accountmaster')),
                ('phone_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.phonebook')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('overdays_count', models.IntegerField()),
                ('cust_due_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_due', to='accounts.masterbranches')),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_due', to='accounting.customermaster')),
            ],
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccountGroups', to='accounting.accounttype'),
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_Balance_dr', models.DecimalField(decimal_places=2, max_digits=9)),
                ('opening_Balance_cr', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tran_total_credit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tran_total_debit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('update_balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('account_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Accounts_balance', to='accounting.accountmaster')),
                ('master_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Accounts_balance', to='accounts.masterbranches')),
            ],
        ),
    ]
