# Generated by Django 3.2 on 2021-05-04 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=35)),
                ('name_en', models.CharField(blank=True, max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no', models.PositiveSmallIntegerField()),
                ('name_ar', models.CharField(max_length=150, unique=True)),
                ('name_en', models.CharField(max_length=150, unique=True)),
                ('reg_no', models.CharField(blank=True, max_length=50)),
                ('vat_no', models.CharField(blank=True, max_length=50)),
                ('main_logo_ar', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('main_logo_en', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('website', models.URLField(blank=True, max_length=100)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=35)),
                ('name_en', models.CharField(blank=True, max_length=35)),
                ('region', models.CharField(blank=True, max_length=35)),
                ('currency', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='JobsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title_ar', models.CharField(max_length=50)),
                ('job_title_en', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=450, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250)),
                ('phone_no_1', models.CharField(blank=True, max_length=15)),
                ('phone_no_2', models.CharField(blank=True, max_length=15)),
                ('fax_no', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('mobile_no_1', models.CharField(blank=True, max_length=15)),
                ('mobile_no_2', models.CharField(blank=True, max_length=15)),
                ('work_phone_no', models.CharField(blank=True, max_length=15)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonebook_phons_city', to='accounts.citymaster')),
            ],
        ),
        migrations.CreateModel(
            name='MohafzaOfCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=35)),
                ('name_en', models.CharField(blank=True, max_length=35)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mohafzaofcity_mohafzes_country', to='accounts.countrymaster')),
            ],
        ),
        migrations.CreateModel(
            name='MasterBranches',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no', models.PositiveSmallIntegerField()),
                ('name_ar', models.CharField(max_length=150, unique=True)),
                ('name_en', models.CharField(max_length=150, unique=True)),
                ('vat_percentag', models.DecimalField(decimal_places=2, max_digits=3)),
                ('main_logo_ar', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('main_logo_en', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('website', models.URLField(blank=True, max_length=100)),
                ('manager_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_credit', models.BooleanField(default=False)),
                ('bank_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterbranches_branches_bank', to='accounts.bankmaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterbranches_branches_company', to='accounts.companymaster')),
            ],
        ),
        migrations.CreateModel(
            name='IDCardMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.BigIntegerField()),
                ('id_source', models.CharField(max_length=20)),
                ('id_end_date', models.DateTimeField()),
                ('responsible_no', models.BigIntegerField()),
                ('responsible_name', models.CharField(max_length=150)),
                ('id_type', models.CharField(choices=[('PI', 'PERSONAL CARD'), ('VI', 'VISA'), ('DR', 'DRIVER LICENSE'), ('WO', 'WORK LICENSE'), ('HI', 'Health Insurance'), ('BI', 'BANK CARD')], default='PERSONAL CARD', max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('phone_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idcardmaster_cards_phone', to='accounts.phonebook')),
            ],
        ),
        migrations.AddField(
            model_name='companymaster',
            name='phone_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companymaster_companies_phone', to='accounts.phonebook'),
        ),
        migrations.AddField(
            model_name='citymaster',
            name='mohafza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citymaster_cites_mohafza', to='accounts.mohafzaofcity'),
        ),
        migrations.CreateModel(
            name='BankBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('bank_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankbranches_branches_bank', to='accounts.bankmaster')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankbranches_banks_city', to='accounts.citymaster')),
            ],
        ),
    ]
