# Generated by Django 3.2 on 2021-05-07 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturnMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_no', models.BigIntegerField()),
                ('invoice_date', models.DateTimeField()),
                ('grand_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('mode_of_pay', models.CharField(choices=[('CAS', 'كاش'), ('CRE', 'اجل')], default='CAS', max_length=3)),
                ('description', models.CharField(max_length=500)),
                ('init_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='accounting.accountmaster')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnty', models.IntegerField(default=1)),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_details', to='product.product')),
                ('return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_details', to='inventory.salesreturnmaster')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.BigIntegerField()),
                ('invoice_date', models.DateTimeField()),
                ('grand_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('mode_of_pay', models.CharField(choices=[('CAS', 'كاش'), ('CRE', 'اجل')], default='CAS', max_length=3)),
                ('description', models.CharField(max_length=500)),
                ('init_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='accounting.accountmaster')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnty', models.IntegerField(default=1)),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoice_details', to='product.product')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoice_details', to='inventory.salesinvoicemaster')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturnMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_no', models.BigIntegerField()),
                ('invoice_date', models.DateTimeField()),
                ('grand_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('mode_of_pay', models.CharField(choices=[('CAS', 'كاش'), ('CRE', 'اجل')], default='CAS', max_length=3)),
                ('description', models.CharField(max_length=500)),
                ('init_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='accounting.accountmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnty', models.IntegerField(default=1)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_return_details', to='product.product')),
                ('return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_return_details', to='inventory.purchasereturnmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.BigIntegerField()),
                ('invoice_date', models.DateTimeField()),
                ('grand_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('mode_of_pay', models.CharField(choices=[('CAS', 'كاش'), ('CRE', 'اجل')], default='CAS', max_length=3)),
                ('description', models.CharField(max_length=500)),
                ('init_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='accounting.accountmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnty', models.IntegerField(default=1)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoice_details', to='product.product')),
                ('pruchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaes_invoice_details', to='inventory.purchaseinvoicemaster')),
            ],
        ),
        migrations.CreateModel(
            name='IncomesVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_no', models.BigIntegerField()),
                ('receipt_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('br_description', models.CharField(max_length=500)),
                ('init_date', models.DateTimeField(auto_now_add=True)),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_incomes', to='accounting.accountmaster')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_incomes', to='accounting.accountmaster')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_no', models.BigIntegerField()),
                ('receipt_date', models.DateTimeField()),
                ('main_code', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cp_description', models.CharField(max_length=500)),
                ('init_date', models.DateTimeField(auto_now_add=True)),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_expenses', to='accounting.accountmaster')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_expenses', to='accounting.accountmaster')),
            ],
        ),
    ]
